addons:
  apt:
    packages:
      - python3.8
      - python3-pip
before_install:
  - gem install bundler
  - pip3 install docutils
  - pip install docutils
dist: bionic
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
